### ISSUE TITLE
hu.dwim updates have broken projectured

### ISSUE THREAD

**Issue by quicklisp** [projectured/projectured#4]
Log is here, though I don't understand exactly what's going on.

http://report.quicklisp.org/2015-04-06/failure-report/projectured.html

Implicit dependencies maybe?

**Comment by projectured** [comment]
Thanks for the report, I'll fix this, I just need to find some time.

**Comment by attila-lendvai** [comment]
Xach, i've unpulled this wave of patches. i will test things locally before pulling them into the live repos next time.

sorry for the mess, things should be back to where they were a month ago!
